# -*- coding: utf-8 -*-
"""Llam-3 finetunig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdzrwVTmNox6LQXlGcbX6pxPi8D4Xm_c
"""

# !pip install -q accelerate peft bitsandbytes transformers trl
# pip install trl
# !mkdir Negotiation_Coach
# # !hf auth login

import os
import torch
import tensorflow as tf
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser,
    TrainingArguments,
    pipeline,
    logging,
)
from peft import LoraConfig, PeftModel
from trl import SFTTrainer

import transformers
import json



# all used variable and hyper parameters are mentioned here

# model
model_name="meta-llama/Llama-3.1-8B"
finetuned_model_name="Llama-3.1-8B-finetuned"

# quntizatoin
use_4bit=True
bnb_4bit_compute_dtype = torch.float16
bnb_4bit_quant_type = "nf4"
use_nested_quant = False

# LoRA
lora_alpha=16
lora_dropout=0.05
lora_r=32

# training arguments
output_dir='./Negotiation_Coach'
epochs=3
fp16=False
bf16=True
per_device_train_batch_size=2
per_device_eval_batch_size=2
gradient_accumulation_steps=8
gradient_checkpointing=True
max_grad_norm=0.3
learning_rate=2e-5
weight_decay=0.001
optimizer="paged_adamw_32bit"
lr_scheduler_type="cosine"
max_steps=-1
warmup_ratio=0.03
group_by_length=True
save_steps=100
logging_steps=25
log_with="tensorboard"
report_to="tensorboard"
seed=42
save_total_limit=3

# sft parameter
max_seq_length=2048
packing=True
device_map="auto"

# load dataset

training_data=[]
validation_data=[]

# training...
with open('./content/negotiation_training.jsonl') as file:
  for record in file:
    training_data.append(json.loads(record))

# validation...
with open('./content/negotiation_validation.jsonl') as file:
  for record in file:
    validation_data.append(json.loads(record))



# start training

# quantization configs
quant_config=BitsAndBytesConfig(
    load_in_4bit=use_4bit,
    bnb_4bit_compute_dtype=bnb_4bit_compute_dtype,
    bnb_4bit_quant_type=bnb_4bit_quant_type,
    bnb_4bit_use_double_quant=use_nested_quant,
)

# loading quantized base model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quant_config,
    device_map=device_map
)
model.config.use_cache=False
model.config.pretraining_tp=1

# loading tokenizer
tokenizer=AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token=tokenizer.eos_token
tokenizer.padding_side="right"


# LoRA configs
lora_config=LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    bias="none",
    task_type="CAUSAL_LM"
)


# training parameters
training_arguments=TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=epochs,
    per_device_train_batch_size=per_device_train_batch_size,
    per_device_eval_batch_size=per_device_eval_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    gradient_checkpointing=gradient_checkpointing,
    optim=optimizer,
    save_steps=save_steps,
    save_total_limit=save_total_limit,
    evaluation_strategy="steps",
    eval_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    weight_decay=weight_decay,
    fp16=fp16,
    bf16=bf16,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=group_by_length,
    lr_scheduler_type=lr_scheduler_type,
    report_to=report_to,
    seed=seed,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False
)


# sft parameter
trainer=SFTTrainer(
    model=model,
    train_dataset=training_data,
    eval_dataset=validation_data,
    peft_config=lora_config,
    tokenizer=tokenizer,
    args=training_arguments,
    max_seq_length=max_seq_length,
    packing=packing,
)

trainer.train()


# save and resume finetuned model

# trainer.save_model("./Negotiation_Coach/final_model")
# tokenizer.save_pretrained("./Negotiation_Coach/final_model")

# trainer.train(resume_from_checkpoint="./checkpoint-300")
# trainer.train(resume_from_checkpoint=True)

# # to load LoRA model fully
# model = AutoModelForCausalLM.from_pretrained(base_model)

# model = PeftModel.from_pretrained(model, "finetuned_model")

# #to merge adapter weights
# model = trainer.model.merge_and_unload()

# model.save_pretrained("merged_model")
# tokenizer.save_pretrained("merged_model")